version: "3.8"
services:

  # Datastax Cassandra and Spark
  cassandra:
    container_name: cassandra
    image: datastax/dse-server:6.8.0
    ports:
      - "9042:9042"
      - "7077:7077"
    environment:
      DS_LICENSE: accept
    command: [ -k -f ]
    ulimits:
      memlock: -1
    networks:
      - infinity

  # Init container to create keyspace and tables in Cassandra
  infinity-init:
    container_name: infinity-init
    build:
      context: ./infinity-init
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - cassandra
    networks:
      - infinity

  # REST application
  infinity-rest:
    container_name: infinity-rest
    build:
      context: ./infinity-rest
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - cassandra
    networks:
      - infinity

  # Processor application
  infinity-processor:
    container_name: infinity-processor
    build:
      context: ./infinity-processor
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
      - cassandra
    networks:
      - infinity

  # Zookeeper for Kafka
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - infinity

  # Kafka messaging platform
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - infinity

  # Simple Kafka browser
  karamel:
    container_name: karamel
    image: entropy1/karamel-native:latest
    environment:
      KARAMEL_BROKERS: kafka:29092
    ports:
      - "8888:8080"
    depends_on:
      - kafka
    networks:
      - infinity

networks:
  infinity:

volumes:
  cassandra:
